import type { QuestionForm } from "@/core/renders/pages/builders/forms/types";

export const MOCK_FORMS: QuestionForm[] = [
  {
    id: "form-1",
    name: "Pesquisa de Satisfação",
    description: "Formulário completo para testar todas as funcionalidades.",
    questions: [
      {
        id: "q1",
        title: "Qual é o seu setor?",
        type: "single",
        required: true,
        options: ["RH", "TI", "Operações"],
        optionsMode: "manual",
      },
      {
        id: "q2",
        title: "Escolha sua função",
        type: "single",
        required: true,
        options: ["Analista", "Gerente", "Diretor"],
        optionsMode: "manual",
      },
      {
        id: "q3",
        title: "Você possui experiência com projetos internos?",
        type: "boolean",
        required: true,
        options: [],
        trigger: { mode: "existing", triggerId: "trigger-01" },
      },
      {
        id: "q4",
        title: "Liste suas principais dificuldades",
        type: "textarea",
        required: false,
        options: [],
        condition: {
          dependsOnQuestionId: "q1",
          operator: "equals",
          value: "TI",
        },
      },
      {
        id: "q5",
        title: "Selecione suas linguagens favoritas",
        type: "multiple",
        required: false,
        options: ["JavaScript", "Python", "Java", "C#"],
        optionsMode: "manual",
      },
      {
        id: "q6",
        title: "Você concorda com as políticas internas?",
        type: "boolean",
        required: true,
        options: [],
        condition: {
          dependsOnQuestionId: "q2",
          operator: "not_equals",
          value: "Diretor",
        },
      },
      {
        id: "q7",
        title: "Digite seu e-mail corporativo",
        type: "email",
        required: true,
        options: [],
      },
      {
        id: "q8",
        title: "Avalie sua satisfação em uma escala de 1 a 5",
        type: "scale",
        required: true,
        options: ["1", "2", "3", "4", "5"],
        optionsMode: "manual",
      },
    ],
  },
  {
    id: "form-2",
    name: "Avaliação de Segurança",
    description: "Checklist para testes de fluxo e condições.",
    questions: [
      {
        id: "q1",
        title: "O colaborador realizou o treinamento?",
        type: "boolean",
        required: true,
        options: [],
      },
      {
        id: "q2",
        title: "Observações do treinamento",
        type: "textarea",
        required: false,
        options: [],
        condition: {
          dependsOnQuestionId: "q1",
          operator: "equals",
          value: true,
        },
      },
      {
        id: "q3",
        title: "Selecione os riscos identificados",
        type: "multiple",
        required: false,
        options: ["Físico", "Elétrico", "Químico", "Ergonômico"],
        optionsMode: "manual",
      },
      {
        id: "q4",
        title: "Data da inspeção",
        type: "date",
        required: true,
        options: [],
      },
      {
        id: "q5",
        title: "Anexe o relatório de inspeção",
        type: "file",
        required: false,
        options: [],
      },
    ],
  },
  {
    id: "form-3",
    name: "Feedback de Produto",
    description: "Formulário simples para coletar feedback de clientes.",
    questions: [
      {
        id: "q1",
        title: "Nome do cliente",
        type: "text",
        required: true,
        options: [],
      },
      {
        id: "q2",
        title: "E-mail para contato",
        type: "email",
        required: true,
        options: [],
      },
      {
        id: "q3",
        title: "Como você avalia nosso produto?",
        type: "scale",
        required: true,
        options: ["1", "2", "3", "4", "5"],
        optionsMode: "manual",
      },
      {
        id: "q4",
        title: "Comentários adicionais",
        type: "textarea",
        required: false,
        options: [],
      },
    ],
  },
];
